webtalk_init -webtalk_dir /home/frank/XilinxProjects/axis_stream_sim/axis_stream_sim.sim/sim_1/behav/xsim/xsim.dir/axis_testbench_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Nov  8 10:55:05 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "fe3b4601-1797-472e-82d8-c12d31a598d2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "7d88a0d0d0d942d6bac61a2dbffb1ef3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "50" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Arch" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Arch Linux" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2666.163 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "7690001 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.09_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "129064_KB" -context "xsim\\usage"
webtalk_transmit -clientid 931088018 -regid "" -xml /home/frank/XilinxProjects/axis_stream_sim/axis_stream_sim.sim/sim_1/behav/xsim/xsim.dir/axis_testbench_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/frank/XilinxProjects/axis_stream_sim/axis_stream_sim.sim/sim_1/behav/xsim/xsim.dir/axis_testbench_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/frank/XilinxProjects/axis_stream_sim/axis_stream_sim.sim/sim_1/behav/xsim/xsim.dir/axis_testbench_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
